
Calculating ELO for NFL Offensive Linemen

```{r}
library(tidyverse)
library(ggplot2)
library(data.table)

#read in data
theme_set(theme_bw())
games <- read_csv("games.csv")
plays <- read_csv("plays.csv")
players <- read_csv("players.csv")
#pffScoutingData <- read_csv("pffScoutingData.csv")
tracking = fread('tracking_week_1.csv')
```

Standardize the 
```{r}

tracking <- tracking |>
  mutate(
    # make all plays go from left to right
    x = ifelse(playDirection == "left", 120 - x, x),
    y = ifelse(playDirection == "left", 160 / 3 - y, y),
    # flip player direction and orientation
    dir = ifelse(playDirection == "left", dir + 180, dir),
    dir = ifelse(dir > 360, dir - 360, dir),
    o = ifelse(playDirection == "left", o + 180, o),
    o = ifelse(o > 360, o - 360, o)
  )
```

Set up NFL field for visualization with sportyR package

```{r}

install.packages("sportyR")
library(sportyR)
field_params <- list(field_apron = "springgreen3",
                     field_border = "springgreen3",
                     offensive_endzone = "springgreen3",
                     defensive_endzone = "springgreen3",
                     offensive_half = "springgreen3",
                     defensive_half = "springgreen3")
nfl_field <- geom_football(league = "nfl",
                           display_range = "in_bounds_only",
                           x_trans = 60,
                           y_trans = 26.6667,
                           xlims = c(35, 85),
                           color_updates = field_params)
nfl_field
```
```{r}

example_play <- tracking |> 
  filter(gameId == 2022091102, playId == 3449) |> 
  mutate(pt_color = case_when(club == "SF" ~ "darkred",
                              club == "CHI" ~ "navy",
                              club == "football" ~ "yellow"))

library(gganimate)
library(gifski)
library(transformr)

head(example_play)

```
```{r}
anim <- nfl_field +  # assumes this is a ggplot object like geom_football(...)
  geom_point(data = example_play,
             aes(x = 120 - x, y = 160/3 - y, color = pt_color),
             size = 3) +
  scale_color_identity() +
  transition_time(frameId) +
  coord_fixed() +
  labs(title = "Frame: {frame_time}")

# Animate and render inline
animate(anim, renderer = gifski_renderer(), width = 800, height = 450)
```


```{r}
nfl_field +
  geom_point(data = example_play %>% filter(frameId == min(frameId)),
             aes(x = 120 - x, y = 160/3 - y, color = pt_color),
             size = 3) +
  scale_color_identity() +
  coord_fixed() +
  theme_minimal()
```
Now we can calculate strain 

```{r}
#get start and end frame for every play in week 1
tracking_start_end <- tracking |>
  distinct(gameId, playId, frameId, event) |>
  mutate(is_start = as.numeric(event %in% c("autoevent_ballsnap", "ball_snap")),
         is_end = as.numeric(event %in% c("fumble", "handoff", "lateral", "autoevent_passforward", 
                                          "pass_forward", "qb_sack", "qb_strip_sack", "run"))) |>
  group_by(gameId, playId) |>
  mutate(any_start = any(is_start == 1), any_end = any(is_end == 1)) |>
  filter(any_start, any_end) |>
  summarize(start_frame = frameId[which(is_start == 1)[1]],
            end_frame = frameId[which(is_end == 1 & frameId > start_frame)[1]]) |>
  ungroup()

#join with original data
tracking <- tracking |>
  left_join(tracking_start_end, by = c("gameId", "playId")) |>
  filter(!is.na(start_frame), !is.na(end_frame),
         frameId >= start_frame, frameId <= end_frame) |>
  mutate(frameId_corrected = frameId - start_frame)
```

```{r}
#get role for each player during play
tracking_roles <- tracking |>
  left_join(players, by = c("nflId")) %>% 
  select(-ends_with(".y")) %>%
  rename_with(~ sub("\\.x$", "", .), ends_with(".x"))

tracking_roles

```

```{r}
#identify QB - different from strain workshop bc no pff scouting data - will do a simple simple filter on position for QB

tracking_qb <- tracking_roles |>
  filter( position == "QB") |>
  select(gameId, playId, frameId, x_qb = x, y_qb = y)

```

```{r}

```

